stage 'Build'
node {
    echo "Groovy:  Build stage:  ";
    git url: 'https://github.com/gpe-mw-training/session-replication.git', credentialsId: ''
    def version = getBuildVersion("pom.xml")
    env.BUILD_VERSION = version
    env.BUILD_GROUP_ID = getGroupIdFromPom("pom.xml")
    env.BUILD_ARTIFACT_ID = getArtifactIdFromPom("pom.xml")
    def branch = 'build-' + version
    env.BUILD_BRANCH = branch
    prepareBuild(version, branch)
    build()
    stash excludes: 'target/', includes: '**', name: 'source'
}

stage 'Integrate'
node {
    unstash 'source'

    // This is where integration tests would be executed
    // integrationTests()    
}

stage 'Publish'
node {
    unstash 'source'

    // This is where your built artifact would be pushed to a Nexus repo
    // For the purpose of the openshift dev course, we'll skip this step
    // publishToNexusAndCommitBranch(env.BUILD_VERSION, env.BUILD_BRANCH)
}

stage 'QA'
node {
    deployToJBossEAP("webapp-qa")
}

stage 'Approve'
timeout(time: 2, unit: 'DAYS') {
    input message: 'Do you want to deploy into production?'
}

stage 'Production'
node {
    deployToJBossEAP("webapp-prod")
}

def checkPort(server, port) {
    sh "checkPort.sh ${server} ${port}"
}

def prepareBuild(version, branch) {
    sh "git checkout -b ${branch}"
    sh "mvn -f pom.xml versions:set -DgenerateBackupPoms=false -DnewVersion=${version} -DOSE_NEXUS_HOST=inf00-mwl.opentlc.com"
}

def build() {   
    sh "mvn clean package -DskipTests -s maven/nexus-hardcoded-settings.xml"
}

def integrationTests() {
    sh "mvn -f pom.xml verify"
}

def publishToNexusAndCommitBranch(version, branch) {
    sh "mvn -f pom.xml deploy -DaltDeploymentRepository=internal.nexus::default::http://nexus:8080/nexus/content/repositories/releases"
    def commit = "Build " + version
    sh "git add **/pom.xml && git commit -m \"${commit}\" && git push origin ${branch}"
}

def deployToJBossEAP(buildConfig) {
    echo "OPENSHIFT_API_URL = $OPENSHIFT_API_URL"
    echo "PROJECT = $PROJECT"
    echo "BUILD_CONFIG = ${buildConfig}"
    sh "oc_build_deploy.sh ${OPENSHIFT_API_URL} ${PROJECT} ${buildConfig}"
}

def getVersionFromPom(pom) {
    def matcher = readFile(pom) =~ '<version>(.+)</version>'
    matcher ? matcher[0][1] : null
}

def getGroupIdFromPom(pom) {
    def matcher = readFile(pom) =~ '<groupId>(.+)</groupId>'
    matcher ? matcher[0][1] : null
 }

def getArtifactIdFromPom(pom) {
    def matcher = readFile(pom) =~ '<artifactId>(.+)</artifactId>'
    matcher ? matcher[0][1] : null
 }

def String getBuildVersion(pom) {
    return getVersionFromPom(pom).minus("-SNAPSHOT") + '.' + env.BUILD_NUMBER
}
